#!/bin/bash

_platform_mattlaptop_match() {

  echo
}


_platform_mattlaptop_setup() {

  echo
}


_platform_perlmutter_match() {

  echo
}


_platform_perlmutter_setup() {

  module load cmake
  module unload darshan/3.1.4
  module load nvidia
}


_scenario_gpu_trial1_mattlaptop() {

  echo
}


_scenario_gpu_trial1_perlmutter() {

  mkdir -p ./build && cd $_

  cmake \
      -DCMAKE_BUILD_TYPE="Release" \
      -DCMAKE_Fortran_FLAGS="-fast -mp=gpu -gpu=cc80 -Mfree" \
      -DCMAKE_Fortran_FLAGS_DEBUG="-Minfo=all" \
    ..

  cd - >/dev/null
}



__setup() {

  _platform_perlmutter_setup
}


__build_and_test() {

  _scenario_gpu_trial1_perlmutter
}



__setup
__build_and_test


