#!/bin/bash

_platform_match_mattlaptop() {

  echo
}


_platform_match_perlmutter() {

  echo
}


_platform_setup_mattlaptop() {

  echo
}


_platform_setup_perlmutter() {

  module load cmake
  module unload darshan/3.1.4
  module load nvidia
}


_scenario_build_gpu_trial1() {

  echo
}


_scenario_test_gpu_trial1() {

  echo
}


__setup() {

  _platform_setup_perlmutter
}


__build() {

  _scenario_build_gpu_trial1
}


__test() {

  _scenario_test_gpu_trial1
}


__setup
__build
__test

